// ═══════════════════════════════════════════════════════════
// Mock data for Module 1 testing
// Will be replaced by real Podman API + registry loader in M2/M3
// ═══════════════════════════════════════════════════════════

export const MOCK_CATEGORIES = [
  { id: "all", label: "All Tools", icon: "Grid" },
  { id: "vulnerability", label: "Vuln Management", icon: "Shield" },
  { id: "siem", label: "SIEM", icon: "Activity" },
  { id: "forensics", label: "Forensics", icon: "Search" },
  { id: "threat-intel", label: "Threat Intel", icon: "Eye" },
  { id: "network", label: "Network", icon: "Network" },
  { id: "utilities", label: "Utilities", icon: "Wrench" },
];

export const STATUS = {
  RUNNING: "running",
  STOPPED: "stopped",
  ERROR: "error",
  UPDATING: "updating",
  STARTING: "starting",
};

export const MOCK_TOOLS = [
  {
    id: "openvas",
    name: "Greenbone OpenVAS",
    category: "vulnerability",
    description: "Full-featured vulnerability scanner with web dashboard. Industry-standard open source VA tool.",
    registry: "docker.io",
    image: "greenbone/community-edition",
    version: "latest",
    compose: true,
    status: STATUS.RUNNING,
    health: "healthy",
    entrypoint: "https://localhost:9392",
    cpu: 12.4,
    mem: 1024,
    ports: [9392],
    uptime: "3d 14h 22m",
  },
  {
    id: "wazuh",
    name: "Wazuh SIEM",
    category: "siem",
    description: "Security information and event management. Intrusion detection, log analysis, and compliance.",
    registry: "docker.io",
    image: "wazuh/wazuh-manager",
    version: "4.7.0",
    compose: true,
    status: STATUS.RUNNING,
    health: "healthy",
    entrypoint: "https://localhost:443",
    cpu: 8.1,
    mem: 2048,
    ports: [443, 1514, 1515],
    uptime: "1d 6h 5m",
  },
  {
    id: "velociraptor",
    name: "Velociraptor",
    category: "forensics",
    description: "Digital forensics and incident response platform. Collect, query, and monitor endpoints.",
    registry: "docker.io",
    image: "velocidex/velociraptor",
    version: "latest",
    compose: false,
    status: STATUS.STOPPED,
    health: null,
    entrypoint: "https://localhost:8889",
    cpu: 0,
    mem: 0,
    ports: [8889, 8000],
    uptime: null,
  },
  {
    id: "misp",
    name: "MISP",
    category: "threat-intel",
    description: "Malware Information Sharing Platform. Threat intelligence sharing and analysis.",
    registry: "docker.io",
    image: "coolacid/misp-docker",
    version: "latest",
    compose: true,
    status: STATUS.ERROR,
    health: "unhealthy",
    entrypoint: "https://localhost:8443",
    cpu: 0,
    mem: 512,
    ports: [8443],
    uptime: null,
  },
  {
    id: "cyberchef",
    name: "CyberChef",
    category: "utilities",
    description: "The Cyber Swiss Army Knife. Data analysis, encoding, decoding, encryption operations.",
    registry: "docker.io",
    image: "mpepping/cyberchef",
    version: "latest",
    compose: false,
    status: STATUS.RUNNING,
    health: "healthy",
    entrypoint: "http://localhost:8080",
    cpu: 0.2,
    mem: 64,
    ports: [8080],
    uptime: "7d 2h 41m",
  },
  {
    id: "portainer",
    name: "Portainer",
    category: "utilities",
    description: "Container management UI. Manage Podman/Docker environments via a web interface.",
    registry: "docker.io",
    image: "portainer/portainer-ce",
    version: "latest",
    compose: false,
    status: STATUS.UPDATING,
    health: null,
    entrypoint: "https://localhost:9443",
    cpu: 1.8,
    mem: 128,
    ports: [9443, 9000],
    uptime: "Updating…",
  },
  {
    id: "zeek",
    name: "Zeek IDS",
    category: "network",
    description: "Network analysis framework. Deep packet inspection, protocol analysis, and network logging.",
    registry: "docker.io",
    image: "zeek/zeek",
    version: "latest",
    compose: false,
    status: STATUS.STOPPED,
    health: null,
    entrypoint: null,
    cpu: 0,
    mem: 0,
    ports: [],
    uptime: null,
  },
];
